# Generated by Django 5.1 on 2024-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_games', models.IntegerField(default=0)),
                ('count_of_wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_game', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(default=' ', max_length=200)),
                ('prize_name', models.CharField(default=' ', max_length=200)),
                ('company', models.CharField(default=' ', max_length=200)),
                ('link', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WinDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_game', models.CharField(max_length=64, unique=True)),
                ('prize_name', models.CharField(default=' ', max_length=200)),
                ('promocode', models.CharField(default=' ', max_length=200)),
                ('company', models.CharField(default=' ', max_length=200)),
                ('link', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
